dist: trusty
language: java
jdk:
- oraclejdk8
install: true
script:
- mvn clean package
deploy:
- provider: s3
  access_key_id: AKIAWQOUZFV6GOS6LIZA
  bucket: atul-test-cbz
  secret_access_key: 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
    
  upload_dir: B16
  cleanup: false
  acl: private
  region: ap-south-1
    
